package dev.aurora.player.app

import dev.aurora.player.domain.ai.AiToolCall
import dev.aurora.player.domain.player.PlayerCommand
import dev.aurora.player.domain.recommendations.RecommendationCandidate
import dev.aurora.player.domain.recommendations.RecommendationEngine
import dev.aurora.player.domain.providers.MusicProvider
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.jsonArray

/**
 * Validates and executes tool calls generated by the AI.
 */
class AiToolExecutor(
    private val playerCoordinator: PlayerCoordinator,
    private val recommendationEngine: RecommendationEngine,
    private val providers: List<MusicProvider>
) {

    private suspend fun resolveItem(trackId: String): dev.aurora.player.domain.models.MediaItem? {
        // Simple resolution strategy: check provider prefix if any, otherwise search or fetch.
        // For YouTube, trackId is youtube:<videoId>
        if (trackId.startsWith("youtube:")) {
            return providers.find { it.id == dev.aurora.player.domain.models.ProviderKind.YOUTUBE }
                ?.resolveMetadata(trackId)?.getOrNull()
        }
        return providers.find { it.id == dev.aurora.player.domain.models.ProviderKind.LOCAL }
            ?.resolveMetadata(trackId)?.getOrNull()
    }

    /**
     * Executes the requested tool. 
     * Returns a list of recommendation candidates if the tool implies a search/recommend operation,
     * or an empty list if it's a direct action (like playback).
     */
    suspend fun executeTool(toolCall: AiToolCall): List<RecommendationCandidate> {
        return when (toolCall.name) {
            "findSimilarMusic" -> {
                // Declared to the model in web/lib/ai/tools.ts. The reference is resolved
                // through a provider first, so an invented id yields nothing rather than
                // seeding recommendations from a track that does not exist.
                val referenceId = toolCall.args["referenceTrackId"]?.jsonPrimitive?.content
                    ?: return emptyList()
                val reference = resolveItem(referenceId) ?: return emptyList()

                recommendationEngine.getRecommendations(
                    query = listOfNotNull(reference.artist, reference.title).joinToString(" "),
                    mood = toolCall.args["mood"]?.jsonPrimitive?.content
                )
            }
            "searchMusic", "recommendMusic" -> {
                val query = toolCall.args["query"]?.jsonPrimitive?.content ?: ""
                val mood = toolCall.args["mood"]?.jsonPrimitive?.content
                val energy = toolCall.args["energy"]?.jsonPrimitive?.content
                
                recommendationEngine.getRecommendations(
                    query = query,
                    mood = mood,
                    energy = energy
                )
            }
            "playTrack" -> {
                val trackId = toolCall.args["trackId"]?.jsonPrimitive?.content ?: return emptyList()
                val mediaItem = resolveItem(trackId)
                if (mediaItem != null) {
                    playerCoordinator.dispatch(PlayerCommand.Load(mediaItem))
                }
                emptyList()
            }
            "addToQueue" -> {
                val trackIds = toolCall.args["trackIds"]?.jsonArray?.map { it.jsonPrimitive.content } ?: return emptyList()
                val items = trackIds.mapNotNull { resolveItem(it) }
                items.forEach {
                    playerCoordinator.dispatch(PlayerCommand.AddToQueue(it))
                }
                emptyList()
            }
            else -> {
                // Ignore unknown tools
                emptyList()
            }
        }
    }
}
