# AURORA Android project properties

# Gradle
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true

# Non-transitive R classes for build performance
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

